# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on: [push, pull_request]

jobs:
  # Run Gradle Wrapper Validation Action to verify the wrapper's checksum
  gradleValidation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

  # Run verifyPlugin and test Gradle tasks
  test:
    name: Test
    needs: gradleValidation
    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_PROJECT_ideaVersion: "${{ matrix.idea_version }}"
      ORG_GRADLE_PROJECT_phpPluginVersion: "${{ matrix.php_plugin_version }}"
      ORG_GRADLE_PROJECT_psiViewerPluginVersion: "${{ matrix.psi_viewer_plugin_version }}"
      ORG_GRADLE_PROJECT_grammarKitPluginVersion: "${{ matrix.grammar_kit_plugin_version }}"
      ORG_GRADLE_PROJECT_customSinceBuild: "${{ matrix.since_build }}"
      ORG_GRADLE_PROJECT_customUntilBuild: "${{ matrix.until_build }}"

    strategy:
      matrix:
        include:
          - idea_version: "IU-2020.3.3"
            java_version: "1.11"
            php_plugin_version: "203.7148.15"
            psi_viewer_plugin_version: "203-SNAPSHOT"
            grammar_kit_plugin_version: "2020.2.1"
            since_build: "203"
            until_build: "203.*"
          - idea_version: "IU-211.6693.14-EAP-SNAPSHOT"
            java_version: "1.11"
            php_plugin_version: "211.6693.25"
            psi_viewer_plugin_version: "211-SNAPSHOT"
            grammar_kit_plugin_version: "2020.2.1"
            since_build: "211"
            until_build: "211.*"

    steps:

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Cache Gradle Dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.idea_version }}-${{ matrix.php_plugin_version }}-gradle-caches-${{ hashFiles('**/*.gradle', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ matrix.idea_version }}-${{ matrix.php_plugin_version }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      # Run detekt, ktlint and tests
      - name: Run Linters and Test
        run: ./gradlew check

      # Run verifyPlugin Gradle task
      - name: Verify Plugin
        run: ./gradlew verifyPlugin

  build:
    name: Build
    needs: test

    env:
      ORG_GRADLE_PROJECT_ideaVersion: "${{ matrix.idea_version }}"
      ORG_GRADLE_PROJECT_phpPluginVersion: "${{ matrix.php_plugin_version }}"
      ORG_GRADLE_PROJECT_psiViewerPluginVersion: "${{ matrix.psi_viewer_plugin_version }}"
      ORG_GRADLE_PROJECT_grammarKitPluginVersion: "${{ matrix.grammar_kit_plugin_version }}"
      ORG_GRADLE_PROJECT_customSinceBuild: "${{ matrix.since_build }}"
      ORG_GRADLE_PROJECT_customUntilBuild: "${{ matrix.until_build }}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - idea_version: "IU-2020.3.3"
            java_version: "1.11"
            php_plugin_version: "203.7148.15"
            psi_viewer_plugin_version: "203-SNAPSHOT"
            grammar_kit_plugin_version: "2020.2.1"
            since_build: "203"
            until_build: "203.*"
          - idea_version: "IU-211.6693.14-EAP-SNAPSHOT"
            java_version: "1.11"
            php_plugin_version: "211.6693.25"
            psi_viewer_plugin_version: "211-SNAPSHOT"
            grammar_kit_plugin_version: "2020.2.1"
            since_build: "211"
            until_build: "211.*"

    outputs:
      name: ${{ steps.properties.outputs.name }}
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
      cms-artifact: ${{ steps.properties.outputs.cms-artifact }}
      fluid-artifact: ${{ steps.properties.outputs.fluid-artifact }}
      typoscript-artifact: ${{ steps.properties.outputs.typoscript-artifact }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}

      # Cache Gradle Dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.idea_version }}-${{ matrix.php_plugin_version }}-gradle-caches-${{ hashFiles('**/*.gradle', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ matrix.idea_version }}-${{ matrix.php_plugin_version }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      # Set environment variables
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
          NAME="$(echo "$PROPERTIES" | grep "^pluginName:" | cut -f2- -d ' ')"
          CHANGELOG="$(./gradlew :getChangelog --unreleased --no-header --console=plain -q)"
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          CMS_ARTIFACT="${NAME}-${VERSION}.zip"
          FLUID_ARTIFACT="${NAME}-${VERSION}.zip"
          TYPOSCRIPT_ARTIFACT="${NAME}-${VERSION}.zip"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=name::$NAME"
          echo "::set-output name=changelog::$CHANGELOG"
          echo "::set-output name=cms-artifact::$CMS_ARTIFACT"
          echo "::set-output name=fluid-artifact::$CMS_ARTIFACT"
          echo "::set-output name=typoscript-artifact::$CMS_ARTIFACT"

      # Build artifact using buildPlugin Gradle task
      - name: Build Plugin
        run: ./gradlew buildPlugin

      # Upload plugin artifact to make it available in the next jobs
      - name: Upload CMS artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: cms-plugin-artifact
          path: ./typo3-cms/build/distributions/${{ steps.properties.outputs.cms-artifact }}
      - name: Upload Fluid artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: fluid-plugin-artifact
          path: ./lang-fluid/build/distributions/${{ steps.properties.outputs.fluid-artifact }}
      - name: Upload TypoScript artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: typoscript-plugin-artifact
          path: ./lang-typoscript/build/distributions/${{ steps.properties.outputs.typoscript-artifact }}

  # Verify built plugin using IntelliJ Plugin Verifier tool
  # Requires build job to be passed
  verify:
    name: Verify
    needs: build
    runs-on: ubuntu-latest
    steps:

      # Setup Java 1.8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Cache Gradle Dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      # Set environment variables
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          IDE_VERSIONS="$(echo "$PROPERTIES" | grep "^pluginVerifierIdeVersions:" | base64)"
          echo "::set-output name=ideVersions::$IDE_VERSIONS"
          echo "::set-output name=pluginVerifierHomeDir::~/.pluginVerifier"
      # Cache Plugin Verifier IDEs
      - name: Setup Plugin Verifier IDEs Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
          key: ${{ runner.os }}-plugin-verifier-${{ steps.properties.outputs.ideVersions }}

  # Prepare a draft release for GitHub Releases page for the manual verification
  # If accepted and published, release workflow would be triggered
  releaseDraft:
    name: Release Draft
    if: github.event_name != 'pull_request'
    needs: [ build, verify ]
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Remove old release drafts by using the curl request for the available releases with draft flag
      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
            | tr '\r\n' ' ' \
            | jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' \
          curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/{}

      # Create new release draft - which is not publicly visible and requires manual acceptance
      - name: Create Release Draft
        id: createDraft
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.version }}
          release_name: v${{ needs.build.outputs.version }}
          body: ${{ needs.build.outputs.changelog }}
          draft: true

      # Download plugin artifact provided by the previous job
      - name: Download CMS Artifact
        uses: actions/download-artifact@v2
        with:
          name: cms-plugin-artifact
      - name: Download Fluid Artifact
        uses: actions/download-artifact@v2
        with:
          name: fluid-plugin-artifact
      - name: Download TypoScript Artifact
        uses: actions/download-artifact@v2
        with:
          name: typoscript-plugin-artifact

      # Upload artifact as a release asset
      - name: Upload CMS Release Asset
        id: upload-cms-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.createDraft.outputs.upload_url }}
          asset_path: ./${{ needs.build.outputs.cms-artifact }}
          asset_name: ${{ needs.build.outputs.cms-artifact }}
          asset_content_type: application/zip
      - name: Upload Fluid Release Asset
        id: upload-release-asset
        uses: actions/upload-fluid-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.createDraft.outputs.upload_url }}
          asset_path: ./${{ needs.build.outputs.fluid-artifact }}
          asset_name: ${{ needs.build.outputs.fluid-artifact }}
          asset_content_type: application/zip
      - name: Upload TypoScript Release Asset
        id: upload-typoscript-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.createDraft.outputs.upload_url }}
          asset_path: ./${{ needs.build.outputs.typoscript-artifact }}
          asset_name: ${{ needs.build.outputs.typoscript-artifact }}
          asset_content_type: application/zip
