# GitHub Actions Workflow created for handling the release process based on the draft release prepared
# with the Build workflow. Running the publishPlugin task requires the PUBLISH_TOKEN secret provided.

name: Release
on:
  release:
    types: [ prereleased, released ]

jobs:

  # Prepare and publish the plugin to the Marketplace repository
  release:
    name: Publish Plugin
    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_PROJECT_ideaVersion: "${{ matrix.idea_version }}"
      ORG_GRADLE_PROJECT_phpPluginVersion: "${{ matrix.php_plugin_version }}"
      ORG_GRADLE_PROJECT_psiViewerPluginVersion: "${{ matrix.psi_viewer_plugin_version }}"
      ORG_GRADLE_PROJECT_grammarKitPluginVersion: "${{ matrix.grammar_kit_plugin_version }}"
      ORG_GRADLE_PROJECT_customSinceBuild: "${{ matrix.since_build }}"
      ORG_GRADLE_PROJECT_customUntilBuild: "${{ matrix.until_build }}"

    strategy:
      matrix:
        include:
          - idea_version: "IU-2022.2.3"
            php_plugin_version: "222.4345.15"
            psi_viewer_plugin_version: "222-SNAPSHOT"
            grammar_kit_plugin_version: "2021.2.2"
            since_build: "222"
            until_build: "222.*"
    outputs:
      prefixed-version: ${{ steps.properties.outputs.prefixed-version }}

    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      # Set environment variables
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^pluginVersion:" | cut -f2- -d ' ')"
          CUSTOM_SINCE_BUILD="$(echo "$PROPERTIES" | grep "^customSinceBuild:" | cut -f2- -d ' ')"
          PREFIXED_VERSION="$(echo ${CUSTOM_SINCE_BUILD}${VERSION:1})"

          echo "::set-output name=prefixed-version::$PREFIXED_VERSION"

      # Publish the plugin to the Marketplace
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        shell: bash
        run: |
          # Set output from previous step
          export "ORG_GRADLE_PROJECT_pluginVersion=${{ steps.properties.outputs.prefixed-version }}"

          ./gradlew :typo3-cms:patchChangelog :typo3-cms:publishPlugin :lang-fluid:publishPlugin :lang-typoscript:publishPlugin

  # Patch changelog, commit and push to the current repository
  changelog:
    name: Update Changelog
    needs: release
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      # Update Unreleased section with the current version
      - name: Patch Changelog
        run: ./gradlew :typo3-cms:patchChangelog

      # Commit patched Changelog
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update changelog" -a
      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
